---
- hosts: all
  become: yes
  gather_facts: yes
  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present
      when: ansible_os_family == "Debian"
    - name: Start Nginx service
      service:
        name: nginx
        state: started
        enabled: yes
      when: ansible_os_family == "Debian"
    - name: Installjavavarfordebian java on debian
      apt:
        name: "{{javavarfordebian}}"
        state: present
      when: ansible_os_family == "Debian"
    - name: Install java on redhat
      yum:
        name: "{{javavarforredhat}}"
        state: present
      when: ansible_os_family == "RedHat"
    - name: Install tomcat on debian
      get_url:
        url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.122/bin/apache-tomcat-9.0.122.tar.gz
        dest: /opt/
      when: ansible_os_family == "Debian"
    - name: Install tomcat on redhat
      get_url:
        url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.122/bin/apache-tomcat-9.0.122.tar.gz
        dest: /opt/
      when: ansible_os_family == "RedHat"
