---
- hosts: all
  become: yes
  gather_facts: yes
  tasks:
   - name: install httpd on redhat
     yum: 
       name: "{{redhatpackagevar}}"
       state: present

     when: ansible_os_family == "RedHat"
   - name: started httpd on redhat
     service: 
       name: "{{stateservicepackage1var}}"
       state: started

     when: ansible_os_family == "RedHat"
   - name: restarted httpd on redhat
     service: 
       name: httpd
       state: restarted

     when: ansible_os_family == "RedHat"

   - name: install apache2 on debian
     apt: 
       name: "{{debianpackagevar}}"
       state: present

     when: ansible_os_family == "Debian"

   - name: started apache2 on debian
     service: 
       name: "{{stateservicepackage2var}}"
       state: started

     when: ansible_os_family == "Debian"
   - name: restarted apache2 on debian
     service: 
       name: apache2
       state: restarted

     when: ansible_os_family == "Debian"
  