---
- hosts: all
  become: yes
  gather_facts: yes
  tasks:
   - include_tasks: myfile.yml
   - name: install apache2 webserver on debian
     apt: 
       name: apache2
       state: present

     when: ansible_os_family == "Debian"
 